# Generated by Django 2.2.2 on 2019-06-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguagem', '0003_auto_20190618_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linguagem',
            name='rank',
            field=models.IntegerField(verbose_name='Rank'),
        ),
    ]
