# Generated by Django 2.2.2 on 2019-06-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguagem', '0004_auto_20190618_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linguagem',
            name='rank',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rank'),
        ),
    ]
